# Generated by Django 6.0.3 on 2026-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="property",
            name="owner",
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(default="Residential", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
    ]
