# Generated by Django 6.0.3 on 2026-03-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_title_property_name_remove_property_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Residential", "Residential"),
                    ("Apartment", "Apartment"),
                    ("Commercial", "Commercial"),
                    ("Land", "Land"),
                ],
                default="Residential",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Inquiry",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
