# Generated by Django 6.0.3 on 2026-04-08 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_inquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(default="unknown@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="name",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="listings.property",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
