# Generated by Django 6.0.3 on 2026-04-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="number_of_rooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="size_sqft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
