# Generated by Django 6.0.3 on 2026-04-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_property_number_of_rooms_property_size_sqft"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualTourScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("scene_key", models.SlugField(max_length=80)),
                (
                    "panorama_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="virtual_tours/"
                    ),
                ),
                ("panorama_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_scenes",
                        to="listings.property",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VirtualTourHotspot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pitch",
                    models.FloatField(help_text="Vertical position, from -90 to 90"),
                ),
                (
                    "yaw",
                    models.FloatField(
                        help_text="Horizontal position, from -180 to 180"
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspots",
                        to="listings.virtualtourscene",
                    ),
                ),
                (
                    "target_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_hotspots",
                        to="listings.virtualtourscene",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="virtualtourscene",
            constraint=models.UniqueConstraint(
                fields=("property", "scene_key"), name="unique_scene_key_per_property"
            ),
        ),
    ]
