# Generated by Django 6.0.3 on 2026-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_virtualtourscene_virtualtourhotspot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="walkthrough_video",
            field=models.FileField(blank=True, null=True, upload_to="property_videos/"),
        ),
    ]
