# Generated by Django 6.0.3 on 2026-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_property_video_url_property_walkthrough_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
