# Generated by Django 6.0.3 on 2026-04-13 07:30

import django.db.models.deletion
from django.db import migrations, models


def copy_property_image_to_propertyimage(apps, schema_editor):
    Property = apps.get_model("listings", "Property")
    PropertyImage = apps.get_model("listings", "PropertyImage")

    for property_obj in Property.objects.exclude(image="").exclude(image__isnull=True):
        PropertyImage.objects.create(property=property_obj, image=property_obj.image)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.property",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(copy_property_image_to_propertyimage, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="property",
            name="image",
        ),
    ]
