# Generated by Django 6.0.3 on 2026-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_remove_property_image_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="number_of_bathrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
