# Generated by Django 6.0.3 on 2026-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0014_alter_property_size_sqft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size_sqft",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Size"
            ),
        ),
    ]
