# Generated by Django 6.0.3 on 2026-04-13 09:55

import re
from django.db import migrations, models


def normalize_size_values(apps, schema_editor):
    Property = apps.get_model("listings", "Property")
    number_pattern = re.compile(r"(\d+(?:\.\d+)?)")

    for property_obj in Property.objects.all():
        raw_size = property_obj.size_sqft
        if raw_size is None:
            continue

        normalized = str(raw_size).replace(",", "").strip().lower()
        if not normalized:
            property_obj.size_sqft = None
            property_obj.save(update_fields=["size_sqft"])
            continue

        if "acre" in normalized:
            property_obj.size_unit = "acres"

        match = number_pattern.search(normalized)
        property_obj.size_sqft = match.group(1) if match else None
        property_obj.save(update_fields=["size_sqft", "size_unit"])


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_alter_property_size_sqft"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="size_unit",
            field=models.CharField(
                choices=[("sqft", "Square Feet"), ("acres", "Acres")],
                default="sqft",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_size_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="property",
            name="size_sqft",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Size",
            ),
        ),
    ]
