# Generated by Django 6.0.3 on 2026-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_property_size_unit_alter_property_size_sqft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size_unit",
            field=models.CharField(
                choices=[
                    ("sqft", "Square Feet"),
                    ("acres", "Acres"),
                    ("perch", "Perch"),
                ],
                default="sqft",
                max_length=20,
            ),
        ),
    ]
