# Generated by Django 6.0.3 on 2026-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0017_alter_property_size_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size_unit",
            field=models.CharField(
                choices=[("sqft", "sqft"), ("acres", "Acres"), ("perch", "Perch")],
                default="sqft",
                max_length=20,
            ),
        ),
    ]
