# Generated by Django 6.0.3 on 2026-04-13 14:40

from django.db import migrations, models


def seed_initial_agents(apps, schema_editor):
    Agent = apps.get_model("listings", "Agent")
    initial_agents = [
        {
            "name": "Malik Jayawardena",
            "specialization": "Senior Executive Partner",
            "email": "malik.jayawardena@shelterandsoul.lk",
            "bio": "With over 12 years of experience in the Colombo luxury market, Malik specializes in high-end colonial estate properties and modern penthouse developments.",
            "deals_closed": "85+",
            "rating": "4.9",
            "volume": "1.2B",
            "photo_url": "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80",
            "is_active": True,
        },
        {
            "name": "Aruni Perera",
            "specialization": "Residential Specialist",
            "email": "aruni.perera@shelterandsoul.lk",
            "bio": "Aruni is known for her exceptional negotiation skills and deep knowledge of upcoming residential zones in the Greater Colombo area.",
            "deals_closed": "120+",
            "rating": "5.0",
            "volume": "850M",
            "photo_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
            "is_active": True,
        },
        {
            "name": "Sahan Wickrama",
            "specialization": "Commercial Consultant",
            "email": "sahan.wickrama@shelterandsoul.lk",
            "bio": "Sahan focuses exclusively on commercial leasing and land acquisition for hospitality projects, serving clients across the southern coast.",
            "deals_closed": "60+",
            "rating": "4.8",
            "volume": "2.1B",
            "photo_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80",
            "is_active": True,
        },
    ]
    for agent_data in initial_agents:
        Agent.objects.get_or_create(name=agent_data["name"], defaults=agent_data)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0018_alter_property_size_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("specialization", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("bio", models.TextField(blank=True)),
                ("deals_closed", models.CharField(blank=True, max_length=30)),
                ("rating", models.CharField(blank=True, max_length=20)),
                ("volume", models.CharField(blank=True, max_length=40)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="agents/"),
                ),
                ("photo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_initial_agents, migrations.RunPython.noop),
    ]
