# Generated by Django 6.0.3 on 2026-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0021_selllead_status_selllead_user_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="selllead",
            name="approval_notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
