# Generated by Django 6.0.3 on 2026-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0023_property_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="listing_category",
            field=models.CharField(
                choices=[("Sell", "Sell"), ("Rent", "Rent")],
                default="Sell",
                max_length=20,
            ),
        ),
    ]
