# Generated by Django 6.0.3 on 2026-04-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0027_searchlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="admin_reply",
            field=models.TextField(
                blank=True, help_text="Admin's reply to this inquiry", null=True
            ),
        ),
    ]
