# Generated by Django 6.0.3 on 2026-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_recentlyviewedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='selllead',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
