# Generated by Django 6.0.3 on 2026-04-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_selllead_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='selllead',
            name='rejection_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
