# Generated by Django 6.0.3 on 2026-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0031_selllead_rejection_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="office_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="personal_contact_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_property_interest",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Buy", "Buy"),
                    ("Rent", "Rent"),
                    ("Sell", "Sell"),
                    ("Invest", "Invest"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="residential_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="short_bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
